# PLEASE ONLY ENTER YOUR PASSPHRASE BELOW IF YOU ARE GOING TO MINE SOLO!
# YOU DO NOT NEED TO ENTER YOUR PASSPHRASE FOR POOL MINING.
# NEVER POST YOUR CONFIG.YAML INCLUDING YOUR PASSPHRASE TO ANY BOARD OR CHAT!




# ********************* 您可能需要修改以下这几个参数 ***********************#

account_id: &numeric_id 12784004271573219481    # 矿工p盘id
plot_size: 10                                  # p盘空间大小 单位是GiB
miner_proportion: 20                            # 矿工分润占比 （0 ～ 100）
account_id_to_secret_phrase:                    # 助记词
  *numeric_id: 'cash mixture tongue cry roof glare monkey island unfair brown spirit inflict'
plot_dirs:                                      # p盘数据存储路径
   - 'data'
url: 'ws://localhost:9948'                 # IPSE节点地址
max_deadline_value: 18446744073709551615                         # 允许的deadline最大提交值
miner_reward_dest: '5FHb1AEeNui5ANvyT368dECmNEJeouLeeZ6a9z8GTvxPLaVs'    # 收益地址(一定要指定)

# ********************* 您可能需要修改以上这几个参数 ***********************#





hdd_reader_thread_count: 0            # default 0 (=auto: number of disks)
hdd_use_direct_io: true               # default true
hdd_wakeup_after: 240                 # default 240s

cpu_threads: 0                        # default 0 (=auto: number of logical cpu cores)
cpu_worker_task_count: 4              # default 4 (0=GPU only)
cpu_nonces_per_cache: 65536           # default 65536
cpu_thread_pinning: false             # default false

gpu_threads: 0                        # default 0 (=GPU off)
gpu_platform: 0                       # default 0
gpu_device: 0                         # default 0
gpu_worker_task_count: 0              # default 0 (=CPU only)
gpu_nonces_per_cache: 262144          # default 262144
gpu_mem_mapping: false                # default false
gpu_async: false                      # default false

target_deadline: 18446744073709551615 # default u32::MAX
account_id_to_target_deadline:        # target dls for multi-id (optional)
 *numeric_id: 18446744073709551615

block_duration: 12000                 # 主网一个区块所需的时间(不要修改)
timeout: 5000                         # default 5000ms
send_proxy_details: true              # default false

console_log_level: 'info'             # default Info, options (off, error, warn, info, debug, trace)
logfile_log_level: 'warn'             # default Warn, options (off, error, warn, info, debug, trace)
logfile_max_count: 10                 # maximum number of log files to keep
logfile_max_size : 20                 # maximum size per logfile in MiB

show_progress: true                   # default true
show_drive_stats: false               # default false
benchmark_only: 'disabled'            # default disabled, options (disabled, I/O, XPU)

# Low noise log patterns
console_log_pattern: "{({d(%H:%M:%S)} [{l}]):16.16} {m}{n}"
logfile_log_pattern: "{({d(%Y-%m-%d %H:%M:%S)} [{l}]):26.26} {m}{n}"

# More detailed log patterns
#console_log_pattern: "{d(%H:%M:%S.%3f%z)} [{h({l}):<5}] [{T}] [{t}] - {M}:{m}{n}"
#logfile_log_pattern: "{d(%Y-%m-%dT%H:%M:%S.%3f%z)} [{h({l}):<5}] [{T}]-[{t}] [{f}:{L}] - {M}:{m}{n}"
