
miners: # 矿工的统一配置
  - {host: localhost, # 远程主机ip
     account_id: 10717349404514113857, # p盘id
     phase: cash mixture tongue cry roof glare monkey island unfair brown spirit inflict, # 私钥
     miner_proportion: 20,  # 矿工分闰占比
     url: 'ws://47.108.199.133:9948',  # 同步节点地址
     plot_size: 50, # p盘大小（单位是Gib）
     miner_reward_dest: 5FHb1AEeNui5ANvyT368dECmNEJeouLeeZ6a9z8GTvxPLaVs, # 矿工受益地址
     plot_path: '/data/test_data',  # p盘位置
     max_deadline_value: 5000,  # deadline最大值
  }

#  - {account_id: 2, phase: hhh, miner_proportion: 20, url: bbb, plot_size: 20,  miner_reward_dest: "sss", plot_path: "/root/data"}
